name: Build OpenWrt Firmware

# Manually trigger the workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build OpenWrt firmware
      run: |
          docker run --rm -i \
            -v "${{ github.workspace }}/bin:/home/build/openwrt/bin" \
            openwrt/imagebuilder:rockchip-armv8-24.10.0-rc5 \
            make image PROFILE=friendlyarm_nanopi-r4s PACKAGES="luci"


    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: /home/build/bin/targets/armv8/rockchip/*   # Adjust this path to match where the firmware is generated
