name: Build OpenWrt Firmware

# Manually trigger the workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Imagebuilder Docker image
        run: docker pull openwrt/imagebuilder:x86-64-openwrt-23.05

      - name: Build Firmware
        run: |
          docker run --rm \
          -v "${{ github.workspace }}/output:/output \
          openwrt/imagebuilder:x86-64-openwrt-23.05 \
          make image PROFILE=x86-64 PACKAGES="luci"

      - name: List Output Directory
        run: ls -la $(pwd)/output

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./output
