name: build-rockchip-openwrt-24.10

on:
  workflow_dispatch:
    inputs:
      profile:
        description: |
          输入 软路由型号（用逗号分隔的多个值），可选值如下：
          ,friendlyarm_nanopi-r4s
          ,friendlyarm_nanopi-r4se
        required: true
        default: 'friendlyarm_nanopi-r4s'
      rootfs_partsize:
        description: '设置软件包大小 单位(MB)'
        required: true
        default: '1024'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/rockchip/build.sh

      - name: Building Rockchip OpenWrt
        run: |
          profiles="${{ github.event.inputs.profile }}"
          rootfs_partsize="${{ github.event.inputs.rootfs_partsize }}"
          
          IFS=',' read -r -a profile_array <<< "$profiles"
          
          for profile in "${profile_array[@]}"; do
            echo "Building for profile: $profile"
            
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/home/build/openwrt/bin" \
              -v "${{ github.workspace }}/files:/home/build/openwrt/files" \
              -v "${{ github.workspace }}/rockchip/openwrt.config:/home/build/openwrt/.config" \
              -v "${{ github.workspace }}/rockchip/build.sh:/home/build/openwrt/build.sh" \
              -e PROFILE=$profile \
              -e ROOTFS_PARTSIZE=$rootfs_partsize \
              
              openwrt/imagebuilder:rockchip-armv8-24.10.0-rc5 /bin/bash /home/build/openwrt/build.sh
          done
      - name: Generate Firmware SHA-256
        run: |
          cp ${{ github.workspace }}/bin/targets/rockchip/armv8/*.img.gz ${{ github.workspace }}
          for file in *.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done

      - name: Create GitHub Release Info
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: Autobuild
          name: OpenWrt-Rockchip
          body_path: ${{ github.workspace }}/info.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload OpenWrt as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: Autobuild
          files: |
            ${{ github.workspace }}/*.img.gz
            ${{ github.workspace }}/*.sha256
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
