name: sunxi-cortexa53-24.10

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Building
        run: |
          mkdir -p bin && chmod 777 bin && \
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/builder/bin:rw" \
              openwrt/imagebuilder:rockchip-armv8-23.05.4 \
              make image PROFILE="friendlyarm_nanopi-r4s"

      - name: Generate Firmware SHA-256
        run: |
          cp ${{ github.workspace }}/bin/targets/rockchip/armv8/*.img.gz ${{ github.workspace }}
          for file in *.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done
      
      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: immortal-R4S-23.05.4
          path: bin/*
