name: immortalWrt-R4S

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Building Rockchip ImmortalWrt
        run: |
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
              -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
              immortalwrt/imagebuilder:rockchip-armv8-openwrt-23.05.4 \
              make image PROFILE="friendlyarm_nanopi-r4s" PACKAGES="ca-bundle dropbear fstools libc libgcc libustream-openssl \
              -fdisk -autocore -automount -luci-app-cpufreq -block-mount -default-settings-chn -kmod-nf-nathelper \
              -kmod-nf-nathelper-extra -luci -luci-compat -luci-lib-base -luci-lib-ipkg -luci-app-opkg" \
              FILES="files" ROOTFS_PARTSIZE="512"
      #- name: checkfile        
      #  run: sh -c "find ${{ github.workspace }}/bin -type f -exec ls -lh {} +"
      - name: List files in bin/targets
        run: ls -lhR ${{ github.workspace }}/bin/targets    
          
      - name: Extract manifest filename and path
        id: get-manifest
        run: |
          MANIFEST_FILE=$(find ${{ github.workspace }}/bin/targets -name "*.manifest" | head -n 1)
          MANIFEST_BASENAME=$(basename "$MANIFEST_FILE" .manifest)
          echo "manifest_file_name=$MANIFEST_BASENAME" >> $GITHUB_ENV
          echo "manifest_file_path=$(dirname "$MANIFEST_FILE")" >> $GITHUB_ENV

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.manifest_file_name }}
          path: ${{ env.manifest_file_path }}
