name: immortalWrt R4S 23.05.4

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Building Rockchip ImmortalWrt
        run: |
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
              -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
              immortalwrt/imagebuilder:rockchip-armv8-openwrt-23.05.4 \
              make image PROFILE="friendlyarm_nanopi-r4s" PACKAGES="ca-bundle dropbear fstools libc libgcc libustream-openssl \
              -fdisk -autocore -automount -luci-app-cpufreq -block-mount -default-settings-chn -kmod-nf-nathelper \
              -kmod-nf-nathelper-extra -luci -luci-compat -luci-lib-base -luci-lib-ipkg -luci-app-opkg" \
              FILES="files" ROOTFS_PARTSIZE="512"
          
      - name: Generate Firmware SHA-256
        run: |
          cp ${{ github.workspace }}/bin/targets/rockchip/armv8/*.img.gz ${{ github.workspace }}
          for file in *.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done
      
      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: immortal-R4S-23.05.4
          path: bin/*

