name: openwrt-R4S

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Building
        run: |
          mkdir -p bin && chmod 777 bin && \
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/builder/bin:rw" \
              openwrt/imagebuilder:rockchip-armv8-23.05.4 \
              make image PROFILE="friendlyarm_nanopi-r4s"
      - name: checkfile        
        run: |       
          ls -lh ${{ github.workspace }}/bin/targets/rockchip/armv8

      - name: Generate Firmware SHA-256
        run: |
          cp ${{ github.workspace }}/bin/targets/rockchip/armv8/*.img.gz ${{ github.workspace }}
          for file in *.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done
          
      - name: Extract manifest filename
        id: get-manifest
        run: |
          MANIFEST_FILE=$(ls ${{ github.workspace }}/bin/targets/rockchip/armv8/*.manifest | head -n 1)
          echo "manifest_file_name=$(basename $MANIFEST_FILE)" >> $GITHUB_ENV

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.manifest_file_name }}
          path: bin/*

