name: openwrt-R4S

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Building
        run: |
          mkdir -p bin && chmod 777 bin && \
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/builder/bin:rw" \
              openwrt/imagebuilder:rockchip-armv8-23.05.4 \
              make image PROFILE="friendlyarm_nanopi-r4s"
              
      #- name: checkfile        
      #  run: ls -lh ${{ github.workspace }}/bin/targets/rockchip/armv8       
      - name: List files in bin/targets
        run: ls -lhR ${{ github.workspace }}/bin/targets    
          
      - name: Extract manifest filename and path
        id: get-manifest
        run: |
          MANIFEST_FILE=$(find ${{ github.workspace }}/bin/targets -name "*.manifest" | head -n 1)
          MANIFEST_BASENAME=$(basename "$MANIFEST_FILE" .manifest)
          echo "manifest_file_name=$MANIFEST_BASENAME" >> $GITHUB_ENV
          echo "manifest_file_path=$(dirname "$MANIFEST_FILE")" >> $GITHUB_ENV

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.manifest_file_name }}
          path: ${{ env.manifest_file_path }}
